version: '3.8'
services:
  myfridge:
    build: .
    volumes:
      - type: bind # バインドマウント（一行で書くとよくない）
        source: ./src
        target: /src
    ports:
      - 3000:3000
    stdin_open: true
    tty: true #コンテナが正常終了してもコンテナを継続させる
    command: npm start
